# Generated by Django 4.0.4 on 2022-05-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro2_app', '0003_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=250),
        ),
    ]
