# Generated by Django 4.0.4 on 2022-05-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro2_app', '0006_alter_student_department_alter_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.IntegerField(),
        ),
    ]
