# Generated by Django 4.0.4 on 2022-05-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro2_app', '0009_alter_student_gpa_alter_student_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='dateOfBirth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('First Level', 'First Level'), ('Second Level', 'Second Level'), ('Third Level', 'Third Level'), ('Fourth Level', 'Fourth Level')], max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileNumber',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
