# Generated by Django 4.0.4 on 2022-05-25 16:15

from django.db import migrations, models
import pro2_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pro2_app', '0015_alter_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='GPA',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[pro2_app.validators.validate_domainonly_GPA]),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[pro2_app.validators.validate_domainonly_id]),
        ),
    ]
